Repository bobbyiliev/introduction-to-bash-scripting, pull requests merged in 2021-10, with the labels that each got.

#26 Add comments to functions
  ebook/en/content/012-bash-functions.md
Labels: hacktoberfest-accepted

#27 Fix a small typo
  ebook/en/content/014-creating-custom-bash-commands.md
Labels: hacktoberfest-accepted

#29 Added Indexing To Readme
  README.md
Labels: hacktoberfest-accepted

#30 Typo fixes :)
  ebook/en/content/019-working-with-cloudflare-api-with-bash.md
Labels: hacktoberfest-accepted

#31 fix typos
  ebook/en/content/019-working-with-cloudflare-api-with-bash.md
  ebook/en/content/020-nginx-and-apache-log-parser.md
Labels: bug, hacktoberfest-accepted

#35 Add Exit status operators
  ebook/en/content/009-bash-conditional-expressions.md
Labels: enhancement, hacktoberfest-accepted

#34 Multiple conditions
  ebook/en/content/010-bash-conditionals.md
Labels: enhancement, hacktoberfest-accepted

#46 Enhanced Readability of the File
  ebook/en/content/004-bash-variables.md
Labels: hacktoberfest-accepted
